on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Push
      run: >
           dotnet nuget push \
           ./location/*.nupkg \
           --source "https://nuget.pkg.github.com/orginization/index.json" \
           --api-key ${{ secrets.NUGET_APIKEY }} --skip-duplicate
